# Generated by Django 6.0.5 on 2026-05-24 02:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('manual', 'Manual'), ('cron', 'Cron')], max_length=10)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('keywords', models.TextField(help_text='Comma separated')),
                ('source', models.CharField(default='youtube', max_length=50)),
                ('amount', models.IntegerField(default=10)),
                ('cycle_days', models.IntegerField(default=7)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.downloadjob')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('filepath', models.CharField(max_length=500)),
                ('video_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('album_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('moved', 'Moved')], default='active', max_length=10)),
                ('needs_tagging', models.BooleanField(default=False)),
                ('pending_confirmation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('jobs', models.ManyToManyField(related_name='songs_added', to='core.downloadjob')),
            ],
        ),
        migrations.CreateModel(
            name='PermanentLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('playlist', models.CharField(blank=True, max_length=255, null=True)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_logs', to='core.song')),
            ],
        ),
    ]
